### ISSUE TITLE
AttributeError while following the quick start steps in the raw project 

### ISSUE THREAD

**Issue by Eggwane** [BLu85/AES-GCM-128-192-256-bits#3]
Hi,

I'm having this error while executing `python3 gcm_config.py --mode 256 --size L --pipe 0`  in the config directory with the raw project : 

```
Traceback (most recent call last):
  File "gcm_config.py", line 11, in <module>
    conf.gcm_ip_config()
  File "/home/rafael/projects/AES-GCM-128-192-256-bits/config/gcm_utils.py", line 227, in gcm_ip_config
    if self.args.seed == None:
AttributeError: 'Namespace' object has no attribute 'seed'
```

I tried this fix : 
```
-        if self.args.seed == None:
+        #if self.args.seed == None: ---> fix because it causes Attribute error 
+        if ~hasattr(self.args, "seed"):
```
but then I'm having troubles whit this seed argument while trying to run `python gcm_testbench.py -m 128 -p 0 -s M -g `. 

Any help would be appreciated. Thanks in advance.

**Comment by BLu85** [comment]
Should be fix now. Let me know

**Comment by Eggwane** [comment]
Works. Thanks a lot for the quick fix, happy to play with your project :)
