### ISSUE TITLE
empty plain text and aad handling

### ISSUE THREAD

**Issue by alphaprobe** [BLu85/AES-GCM-128-192-256-bits#7]
In tb/gcm_gctr.py the comparison with 'empty' is incorrect. The comparison should be done with 'EMPTY' as thats how the json file gets created with 'empty'  with -a switch.

**Comment by BLu85** [comment]
Good point. I'll change that.
Thanks for spotting and reporting it.
Cheers.

**Comment by BLu85** [comment]
I'll close this issue as it has been fixed in version 1.8
